name: Ruta
favicon: null
layout_spectrum: 0.14121097838506103
typography_spectrum: 0.09878447698429227
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.864517180249095
  lightness: 0.9973878792952746
  saturation: 0.9178850778844208
  rhythmicContrast: 0.6002597706392407
purpose: []
